### ISSUE TITLE
Allow other monads than Future e.g Cats.IO

### ISSUE THREAD

**Issue by dwlizlo** [outr/scarango#23]
Enabling code to use Cats.IO would make it much more pleasent to work with some libraries (http4s for instance).

I was wondering how big of the effort would it be? Is it feasible at all?

**Comment by darkfrog26** [comment]
I try to keep the third-party libraries to a minimum in my open-source libraries because they can create issues for people using different versions in their own projects. In addition, I'm not really a fan of http4s. I used to use it, but it had a lot of underlying problems, so I ended up writing my own system (youi.io).

If you strongly believe it's worthwhile, I'm open to considering it though.

**Comment by dwlizlo** [comment]
@darkfrog26 So my idea was not to replace Futures with IO, but rather make the monads "pluggable". I believe http4s let's you use arbitrary F[_], but they opt for IO by default?

**Comment by darkfrog26** [comment]
Can you clarify the gains this would provide? I can appreciate making it an abstraction, but doesn't Cats already have implicits that can convert from/to `Future`?

**Comment by dwlizlo** [comment]
[Futures are eager where IO are lazy.](https://typelevel.org/cats-effect/datatypes/io.html#on-referential-transparency-and-lazy-evaluation)
Unfortunatelly there is no implicit conversion for this ([more on why not](https://github.com/typelevel/cats-effect/issues/173)).

IMO biggest gain for using either of those is better composability. Mixing IO and Future can lead to tidious conversions and it's possible to get it wrong, so maybe it's best to avoid it.

**Comment by darkfrog26** [comment]
Would you be interested in putting together a PR for this?

**Comment by darkfrog26** [comment]
FYI, this will be coming soon.

**Comment by dwlizlo** [comment]
Hey, I switched to postgres lately. I will close the issue.
Good to know it's coming thought!
